version: '3.4'

services:

 gateway.web.api:
    image: ${DOCKER_REGISTRY-}gateway-api
    build:
      context: .
      dockerfile: src/Gateways/Gateway.Ocelot.Api/Dockerfile
    container_name: gateway-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Europe/Khmelnytskyi
    ports:
      - "11000:80"

 postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "10100:5432"
    environment:
      POSTGRES_PASSWORD: 123258

 closemate.api:
    image: ${DOCKER_REGISTRY-}closemate-api
    build:
      context: .
      dockerfile: src/Services/CloseMate.Api/Dockerfile
    container_name: closemate-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TZ=Europe/Khmelnytskyi
    ports:
      - "20001:80"